### ISSUE TITLE
How to make sure we use the latest EDK2 version

### ISSUE THREAD

**Issue by startergo** [xaionaro/edk2-builder-docker#30]
Is this executed on every run of docker machine or only during build and push to Docker registry?

https://github.com/xaionaro/edk2-builder-docker/blob/main/Dockerfile#L70-L71

If the edk2 repo has any changes will the docker machine need to be pushed to registry or will it grab the latest edk2 repo on every run regardless?

https://github.com/xaionaro/edk2-builder-docker/blob/main/clone-edk2.sh#L8-L9

**Comment by xaionaro** [comment]
> Is this executed on every run of docker machine or only during build and push to Docker registry?

Only on building. It allows to avoid waiting of [EDK2 building process](https://github.com/xaionaro/edk2-builder-docker/blob/main/build-edk2.sh) on the user's end (because everything is already pre-built).

One more important reason: it provides more deterministic results (so the end user and we use the exact same version of EDK2 and thus get the same result)

> If the edk2 repo has any changes will the docker machine need to be pushed to registry or will it grab the latest edk2 repo on every run regardless?

We automatically rebuild docker images (which depends on this kind of repositories) once a week (we can do it more often if required):
https://github.com/xaionaro/edk2-builder-docker/actions/workflows/github-actions-force-push-latests.yml

So the user just need to pull a new image. This is why it is important to execute:
```
docker pull xaionaro2/edk2-builder:<the EDK2 tag>
```
in the example-scripts :)

**Comment by startergo** [comment]
> we can do it more often if required

No need. It can be pushed manually through actions.

**Comment by xaionaro** [comment]
Closing for now. Feel free to reopen :)
